# Accommodate the full institution/campus hostname in the shared HTTP context.
server_names_hash_bucket_size 128;

server {
    listen 80;
    server_name aquilino-duran-pedro-fortoul.162.35.28.193.nip.io;
    client_max_body_size 10M;
    location / {
        proxy_pass http://aqd-pf-web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
